CREATE TABLE [dbo].[Uploader](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[_id] [nvarchar](128) NOT NULL,
	[username] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Uploader] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO